name: Deployment

on:
  workflow_dispatch: null
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy (Staging)
    runs-on: ubuntu-latest
    environment: Healthier-Staging
    steps:
      - name: checkout
        uses: actions/checkout@master


      - name: create env file
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env


      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: mkdir -p ~/srv/ubuntu
      

      - name: copy docker-compose via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "docker-compose.staging.yml,.env"
          target: ~/srv/ubuntu

